# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # aliased to a recent 7.x version
  - 7.0
  - 7.1
  - 7.2
  # aliased to a recent hhvm version
  - hhvm

# optionally set up exclutions and allowed failures in the matrix
matrix:
  allow_failures:
    - php: hhvm

 # execute any number of scripts before the test run, custom env's are available as variables
install:
  - composer install

# execute tests
script:
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpmd src,tests text phpmd.xml --suffixes php
  - php vendor/bin/codecept run --coverage --coverage-xml

# upload coverage to scrutinizer
after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml; fi
